
#include "qgl.h"
#include "gl_local.h"

void ( APIENTRY * qglAccum )(GLenum op, GLfloat value);
void ( APIENTRY * qglAlphaFunc )(GLenum func, GLclampf ref);
GLboolean ( APIENTRY * qglAreTexturesResident )(GLsizei n, const GLuint *textures, GLboolean *residences);
void ( APIENTRY * qglArrayElement )(GLint i);
void ( APIENTRY * qglBegin )(GLenum mode);
void ( APIENTRY * qglBindTexture )(GLenum target, GLuint texture);
void ( APIENTRY * qglBitmap )(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
void ( APIENTRY * qglBlendFunc )(GLenum sfactor, GLenum dfactor);
void ( APIENTRY * qglCallList )(GLuint list);
void ( APIENTRY * qglCallLists )(GLsizei n, GLenum type, const GLvoid *lists);
void ( APIENTRY * qglClear )(GLbitfield mask);
void ( APIENTRY * qglClearAccum )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglClearColor )(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void ( APIENTRY * qglClearDepth )(GLclampd depth);
void ( APIENTRY * qglClearIndex )(GLfloat c);
void ( APIENTRY * qglClearStencil )(GLint s);
void ( APIENTRY * qglClipPlane )(GLenum plane, const GLdouble *equation);
void ( APIENTRY * qglColor3b )(GLbyte red, GLbyte green, GLbyte blue);
void ( APIENTRY * qglColor3bv )(const GLbyte *v);
void ( APIENTRY * qglColor3d )(GLdouble red, GLdouble green, GLdouble blue);
void ( APIENTRY * qglColor3dv )(const GLdouble *v);
void ( APIENTRY * qglColor3f )(GLfloat red, GLfloat green, GLfloat blue);
void ( APIENTRY * qglColor3fv )(const GLfloat *v);
void ( APIENTRY * qglColor3i )(GLint red, GLint green, GLint blue);
void ( APIENTRY * qglColor3iv )(const GLint *v);
void ( APIENTRY * qglColor3s )(GLshort red, GLshort green, GLshort blue);
void ( APIENTRY * qglColor3sv )(const GLshort *v);
void ( APIENTRY * qglColor3ub )(GLubyte red, GLubyte green, GLubyte blue);
void ( APIENTRY * qglColor3ubv )(const GLubyte *v);
void ( APIENTRY * qglColor3ui )(GLuint red, GLuint green, GLuint blue);
void ( APIENTRY * qglColor3uiv )(const GLuint *v);
void ( APIENTRY * qglColor3us )(GLushort red, GLushort green, GLushort blue);
void ( APIENTRY * qglColor3usv )(const GLushort *v);
void ( APIENTRY * qglColor4b )(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
void ( APIENTRY * qglColor4bv )(const GLbyte *v);
void ( APIENTRY * qglColor4d )(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
void ( APIENTRY * qglColor4dv )(const GLdouble *v);
void ( APIENTRY * qglColor4f )(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void ( APIENTRY * qglColor4fv )(const GLfloat *v);
void ( APIENTRY * qglColor4i )(GLint red, GLint green, GLint blue, GLint alpha);
void ( APIENTRY * qglColor4iv )(const GLint *v);
void ( APIENTRY * qglColor4s )(GLshort red, GLshort green, GLshort blue, GLshort alpha);
void ( APIENTRY * qglColor4sv )(const GLshort *v);
void ( APIENTRY * qglColor4ub )(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
void ( APIENTRY * qglColor4ubv )(const GLubyte *v);
void ( APIENTRY * qglColor4ui )(GLuint red, GLuint green, GLuint blue, GLuint alpha);
void ( APIENTRY * qglColor4uiv )(const GLuint *v);
void ( APIENTRY * qglColor4us )(GLushort red, GLushort green, GLushort blue, GLushort alpha);
void ( APIENTRY * qglColor4usv )(const GLushort *v);
void ( APIENTRY * qglColorMask )(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void ( APIENTRY * qglColorMaterial )(GLenum face, GLenum mode);
void ( APIENTRY * qglColorPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglCopyPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void ( APIENTRY * qglCopyTexImage1D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
void ( APIENTRY * qglCopyTexImage2D )(GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void ( APIENTRY * qglCopyTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
void ( APIENTRY * qglCopyTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglCullFace )(GLenum mode);
void ( APIENTRY * qglDeleteLists )(GLuint list, GLsizei range);
void ( APIENTRY * qglDeleteTextures )(GLsizei n, const GLuint *textures);
void ( APIENTRY * qglDepthFunc )(GLenum func);
void ( APIENTRY * qglDepthMask )(GLboolean flag);
void ( APIENTRY * qglDepthRange )(GLclampd zNear, GLclampd zFar);
void ( APIENTRY * qglDisable )(GLenum cap);
void ( APIENTRY * qglDisableClientState )(GLenum array);
void ( APIENTRY * qglDrawArrays )(GLenum mode, GLint first, GLsizei count);
void ( APIENTRY * qglDrawBuffer )(GLenum mode);
void ( APIENTRY * qglDrawElements )(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
void ( APIENTRY * qglDrawPixels )(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglEdgeFlag )(GLboolean flag);
void ( APIENTRY * qglEdgeFlagPointer )(GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglEdgeFlagv )(const GLboolean *flag);
void ( APIENTRY * qglEnable )(GLenum cap);
void ( APIENTRY * qglEnableClientState )(GLenum array);
void ( APIENTRY * qglEnd )(void);
void ( APIENTRY * qglEndList )(void);
void ( APIENTRY * qglEvalCoord1d )(GLdouble u);
void ( APIENTRY * qglEvalCoord1dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord1f )(GLfloat u);
void ( APIENTRY * qglEvalCoord1fv )(const GLfloat *u);
void ( APIENTRY * qglEvalCoord2d )(GLdouble u, GLdouble v);
void ( APIENTRY * qglEvalCoord2dv )(const GLdouble *u);
void ( APIENTRY * qglEvalCoord2f )(GLfloat u, GLfloat v);
void ( APIENTRY * qglEvalCoord2fv )(const GLfloat *u);
void ( APIENTRY * qglEvalMesh1 )(GLenum mode, GLint i1, GLint i2);
void ( APIENTRY * qglEvalMesh2 )(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
void ( APIENTRY * qglEvalPoint1 )(GLint i);
void ( APIENTRY * qglEvalPoint2 )(GLint i, GLint j);
void ( APIENTRY * qglFeedbackBuffer )(GLsizei size, GLenum type, GLfloat *buffer);
void ( APIENTRY * qglFinish )(void);
void ( APIENTRY * qglFlush )(void);
void ( APIENTRY * qglFogf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglFogfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglFogi )(GLenum pname, GLint param);
void ( APIENTRY * qglFogiv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglFrontFace )(GLenum mode);
void ( APIENTRY * qglFrustum )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
GLuint ( APIENTRY * qglGenLists )(GLsizei range);
void ( APIENTRY * qglGenTextures )(GLsizei n, GLuint *textures);
void ( APIENTRY * qglGetBooleanv )(GLenum pname, GLboolean *params);
void ( APIENTRY * qglGetClipPlane )(GLenum plane, GLdouble *equation);
void ( APIENTRY * qglGetDoublev )(GLenum pname, GLdouble *params);
GLenum ( APIENTRY * qglGetError )(void);
void ( APIENTRY * qglGetFloatv )(GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetIntegerv )(GLenum pname, GLint *params);
void ( APIENTRY * qglGetLightfv )(GLenum light, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetLightiv )(GLenum light, GLenum pname, GLint *params);
void ( APIENTRY * qglGetMapdv )(GLenum target, GLenum query, GLdouble *v);
void ( APIENTRY * qglGetMapfv )(GLenum target, GLenum query, GLfloat *v);
void ( APIENTRY * qglGetMapiv )(GLenum target, GLenum query, GLint *v);
void ( APIENTRY * qglGetMaterialfv )(GLenum face, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetMaterialiv )(GLenum face, GLenum pname, GLint *params);
void ( APIENTRY * qglGetPixelMapfv )(GLenum map, GLfloat *values);
void ( APIENTRY * qglGetPixelMapuiv )(GLenum map, GLuint *values);
void ( APIENTRY * qglGetPixelMapusv )(GLenum map, GLushort *values);
void ( APIENTRY * qglGetPointerv )(GLenum pname, GLvoid* *params);
void ( APIENTRY * qglGetPolygonStipple )(GLubyte *mask);
const GLubyte * ( APIENTRY * qglGetString )(GLenum name);
void ( APIENTRY * qglGetTexEnvfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexEnviv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexGendv )(GLenum coord, GLenum pname, GLdouble *params);
void ( APIENTRY * qglGetTexGenfv )(GLenum coord, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexGeniv )(GLenum coord, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexImage )(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglGetTexLevelParameterfv )(GLenum target, GLint level, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexLevelParameteriv )(GLenum target, GLint level, GLenum pname, GLint *params);
void ( APIENTRY * qglGetTexParameterfv )(GLenum target, GLenum pname, GLfloat *params);
void ( APIENTRY * qglGetTexParameteriv )(GLenum target, GLenum pname, GLint *params);
void ( APIENTRY * qglHint )(GLenum target, GLenum mode);
void ( APIENTRY * qglIndexMask )(GLuint mask);
void ( APIENTRY * qglIndexPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglIndexd )(GLdouble c);
void ( APIENTRY * qglIndexdv )(const GLdouble *c);
void ( APIENTRY * qglIndexf )(GLfloat c);
void ( APIENTRY * qglIndexfv )(const GLfloat *c);
void ( APIENTRY * qglIndexi )(GLint c);
void ( APIENTRY * qglIndexiv )(const GLint *c);
void ( APIENTRY * qglIndexs )(GLshort c);
void ( APIENTRY * qglIndexsv )(const GLshort *c);
void ( APIENTRY * qglIndexub )(GLubyte c);
void ( APIENTRY * qglIndexubv )(const GLubyte *c);
void ( APIENTRY * qglInitNames )(void);
void ( APIENTRY * qglInterleavedArrays )(GLenum format, GLsizei stride, const GLvoid *pointer);
GLboolean ( APIENTRY * qglIsEnabled )(GLenum cap);
GLboolean ( APIENTRY * qglIsList )(GLuint list);
GLboolean ( APIENTRY * qglIsTexture )(GLuint texture);
void ( APIENTRY * qglLightModelf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglLightModelfv )(GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLightModeli )(GLenum pname, GLint param);
void ( APIENTRY * qglLightModeliv )(GLenum pname, const GLint *params);
void ( APIENTRY * qglLightf )(GLenum light, GLenum pname, GLfloat param);
void ( APIENTRY * qglLightfv )(GLenum light, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglLighti )(GLenum light, GLenum pname, GLint param);
void ( APIENTRY * qglLightiv )(GLenum light, GLenum pname, const GLint *params);
void ( APIENTRY * qglLineStipple )(GLint factor, GLushort pattern);
void ( APIENTRY * qglLineWidth )(GLfloat width);
void ( APIENTRY * qglListBase )(GLuint base);
void ( APIENTRY * qglLoadIdentity )(void);
void ( APIENTRY * qglLoadMatrixd )(const GLdouble *m);
void ( APIENTRY * qglLoadMatrixf )(const GLfloat *m);
void ( APIENTRY * qglLoadName )(GLuint name);
void ( APIENTRY * qglLogicOp )(GLenum opcode);
void ( APIENTRY * qglMap1d )(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
void ( APIENTRY * qglMap1f )(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
void ( APIENTRY * qglMap2d )(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
void ( APIENTRY * qglMap2f )(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
void ( APIENTRY * qglMapGrid1d )(GLint un, GLdouble u1, GLdouble u2);
void ( APIENTRY * qglMapGrid1f )(GLint un, GLfloat u1, GLfloat u2);
void ( APIENTRY * qglMapGrid2d )(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
void ( APIENTRY * qglMapGrid2f )(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
void ( APIENTRY * qglMaterialf )(GLenum face, GLenum pname, GLfloat param);
void ( APIENTRY * qglMaterialfv )(GLenum face, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglMateriali )(GLenum face, GLenum pname, GLint param);
void ( APIENTRY * qglMaterialiv )(GLenum face, GLenum pname, const GLint *params);
void ( APIENTRY * qglMatrixMode )(GLenum mode);
void ( APIENTRY * qglMultMatrixd )(const GLdouble *m);
void ( APIENTRY * qglMultMatrixf )(const GLfloat *m);
void ( APIENTRY * qglNewList )(GLuint list, GLenum mode);
void ( APIENTRY * qglNormal3b )(GLbyte nx, GLbyte ny, GLbyte nz);
void ( APIENTRY * qglNormal3bv )(const GLbyte *v);
void ( APIENTRY * qglNormal3d )(GLdouble nx, GLdouble ny, GLdouble nz);
void ( APIENTRY * qglNormal3dv )(const GLdouble *v);
void ( APIENTRY * qglNormal3f )(GLfloat nx, GLfloat ny, GLfloat nz);
void ( APIENTRY * qglNormal3fv )(const GLfloat *v);
void ( APIENTRY * qglNormal3i )(GLint nx, GLint ny, GLint nz);
void ( APIENTRY * qglNormal3iv )(const GLint *v);
void ( APIENTRY * qglNormal3s )(GLshort nx, GLshort ny, GLshort nz);
void ( APIENTRY * qglNormal3sv )(const GLshort *v);
void ( APIENTRY * qglNormalPointer )(GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglOrtho )(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
void ( APIENTRY * qglPassThrough )(GLfloat token);
void ( APIENTRY * qglPixelMapfv )(GLenum map, GLsizei mapsize, const GLfloat *values);
void ( APIENTRY * qglPixelMapuiv )(GLenum map, GLsizei mapsize, const GLuint *values);
void ( APIENTRY * qglPixelMapusv )(GLenum map, GLsizei mapsize, const GLushort *values);
void ( APIENTRY * qglPixelStoref )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelStorei )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelTransferf )(GLenum pname, GLfloat param);
void ( APIENTRY * qglPixelTransferi )(GLenum pname, GLint param);
void ( APIENTRY * qglPixelZoom )(GLfloat xfactor, GLfloat yfactor);
void ( APIENTRY * qglPointSize )(GLfloat size);
void ( APIENTRY * qglPolygonMode )(GLenum face, GLenum mode);
void ( APIENTRY * qglPolygonOffset )(GLfloat factor, GLfloat units);
void ( APIENTRY * qglPolygonStipple )(const GLubyte *mask);
void ( APIENTRY * qglPopAttrib )(void);
void ( APIENTRY * qglPopClientAttrib )(void);
void ( APIENTRY * qglPopMatrix )(void);
void ( APIENTRY * qglPopName )(void);
void ( APIENTRY * qglPrioritizeTextures )(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void ( APIENTRY * qglPushAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushClientAttrib )(GLbitfield mask);
void ( APIENTRY * qglPushMatrix )(void);
void ( APIENTRY * qglPushName )(GLuint name);
void ( APIENTRY * qglRasterPos2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglRasterPos2dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglRasterPos2fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos2i )(GLint x, GLint y);
void ( APIENTRY * qglRasterPos2iv )(const GLint *v);
void ( APIENTRY * qglRasterPos2s )(GLshort x, GLshort y);
void ( APIENTRY * qglRasterPos2sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRasterPos3dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglRasterPos3fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglRasterPos3iv )(const GLint *v);
void ( APIENTRY * qglRasterPos3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglRasterPos3sv )(const GLshort *v);
void ( APIENTRY * qglRasterPos4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglRasterPos4dv )(const GLdouble *v);
void ( APIENTRY * qglRasterPos4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglRasterPos4fv )(const GLfloat *v);
void ( APIENTRY * qglRasterPos4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglRasterPos4iv )(const GLint *v);
void ( APIENTRY * qglRasterPos4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglRasterPos4sv )(const GLshort *v);
void ( APIENTRY * qglReadBuffer )(GLenum mode);
void ( APIENTRY * qglReadPixels )(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
void ( APIENTRY * qglRectd )(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
void ( APIENTRY * qglRectdv )(const GLdouble *v1, const GLdouble *v2);
void ( APIENTRY * qglRectf )(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
void ( APIENTRY * qglRectfv )(const GLfloat *v1, const GLfloat *v2);
void ( APIENTRY * qglRecti )(GLint x1, GLint y1, GLint x2, GLint y2);
void ( APIENTRY * qglRectiv )(const GLint *v1, const GLint *v2);
void ( APIENTRY * qglRects )(GLshort x1, GLshort y1, GLshort x2, GLshort y2);
void ( APIENTRY * qglRectsv )(const GLshort *v1, const GLshort *v2);
GLint ( APIENTRY * qglRenderMode )(GLenum mode);
void ( APIENTRY * qglRotated )(GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglRotatef )(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScaled )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglScalef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglScissor )(GLint x, GLint y, GLsizei width, GLsizei height);
void ( APIENTRY * qglSelectBuffer )(GLsizei size, GLuint *buffer);
void ( APIENTRY * qglShadeModel )(GLenum mode);
void ( APIENTRY * qglStencilFunc )(GLenum func, GLint ref, GLuint mask);
void ( APIENTRY * qglStencilMask )(GLuint mask);
void ( APIENTRY * qglStencilOp )(GLenum fail, GLenum zfail, GLenum zpass);
void ( APIENTRY * qglTexCoord1d )(GLdouble s);
void ( APIENTRY * qglTexCoord1dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord1f )(GLfloat s);
void ( APIENTRY * qglTexCoord1fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord1i )(GLint s);
void ( APIENTRY * qglTexCoord1iv )(const GLint *v);
void ( APIENTRY * qglTexCoord1s )(GLshort s);
void ( APIENTRY * qglTexCoord1sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord2d )(GLdouble s, GLdouble t);
void ( APIENTRY * qglTexCoord2dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord2f )(GLfloat s, GLfloat t);
void ( APIENTRY * qglTexCoord2fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord2i )(GLint s, GLint t);
void ( APIENTRY * qglTexCoord2iv )(const GLint *v);
void ( APIENTRY * qglTexCoord2s )(GLshort s, GLshort t);
void ( APIENTRY * qglTexCoord2sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord3d )(GLdouble s, GLdouble t, GLdouble r);
void ( APIENTRY * qglTexCoord3dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord3f )(GLfloat s, GLfloat t, GLfloat r);
void ( APIENTRY * qglTexCoord3fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord3i )(GLint s, GLint t, GLint r);
void ( APIENTRY * qglTexCoord3iv )(const GLint *v);
void ( APIENTRY * qglTexCoord3s )(GLshort s, GLshort t, GLshort r);
void ( APIENTRY * qglTexCoord3sv )(const GLshort *v);
void ( APIENTRY * qglTexCoord4d )(GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void ( APIENTRY * qglTexCoord4dv )(const GLdouble *v);
void ( APIENTRY * qglTexCoord4f )(GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void ( APIENTRY * qglTexCoord4fv )(const GLfloat *v);
void ( APIENTRY * qglTexCoord4i )(GLint s, GLint t, GLint r, GLint q);
void ( APIENTRY * qglTexCoord4iv )(const GLint *v);
void ( APIENTRY * qglTexCoord4s )(GLshort s, GLshort t, GLshort r, GLshort q);
void ( APIENTRY * qglTexCoord4sv )(const GLshort *v);
void ( APIENTRY * qglTexCoordPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglTexEnvf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexEnvfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexEnvi )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexEnviv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexGend )(GLenum coord, GLenum pname, GLdouble param);
void ( APIENTRY * qglTexGendv )(GLenum coord, GLenum pname, const GLdouble *params);
void ( APIENTRY * qglTexGenf )(GLenum coord, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexGenfv )(GLenum coord, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexGeni )(GLenum coord, GLenum pname, GLint param);
void ( APIENTRY * qglTexGeniv )(GLenum coord, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexImage1D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexImage2D )(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexParameterf )(GLenum target, GLenum pname, GLfloat param);
void ( APIENTRY * qglTexParameterfv )(GLenum target, GLenum pname, const GLfloat *params);
void ( APIENTRY * qglTexParameteri )(GLenum target, GLenum pname, GLint param);
void ( APIENTRY * qglTexParameteriv )(GLenum target, GLenum pname, const GLint *params);
void ( APIENTRY * qglTexSubImage1D )(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTexSubImage2D )(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
void ( APIENTRY * qglTranslated )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglTranslatef )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex2d )(GLdouble x, GLdouble y);
void ( APIENTRY * qglVertex2dv )(const GLdouble *v);
void ( APIENTRY * qglVertex2f )(GLfloat x, GLfloat y);
void ( APIENTRY * qglVertex2fv )(const GLfloat *v);
void ( APIENTRY * qglVertex2i )(GLint x, GLint y);
void ( APIENTRY * qglVertex2iv )(const GLint *v);
void ( APIENTRY * qglVertex2s )(GLshort x, GLshort y);
void ( APIENTRY * qglVertex2sv )(const GLshort *v);
void ( APIENTRY * qglVertex3d )(GLdouble x, GLdouble y, GLdouble z);
void ( APIENTRY * qglVertex3dv )(const GLdouble *v);
void ( APIENTRY * qglVertex3f )(GLfloat x, GLfloat y, GLfloat z);
void ( APIENTRY * qglVertex3fv )(const GLfloat *v);
void ( APIENTRY * qglVertex3i )(GLint x, GLint y, GLint z);
void ( APIENTRY * qglVertex3iv )(const GLint *v);
void ( APIENTRY * qglVertex3s )(GLshort x, GLshort y, GLshort z);
void ( APIENTRY * qglVertex3sv )(const GLshort *v);
void ( APIENTRY * qglVertex4d )(GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void ( APIENTRY * qglVertex4dv )(const GLdouble *v);
void ( APIENTRY * qglVertex4f )(GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void ( APIENTRY * qglVertex4fv )(const GLfloat *v);
void ( APIENTRY * qglVertex4i )(GLint x, GLint y, GLint z, GLint w);
void ( APIENTRY * qglVertex4iv )(const GLint *v);
void ( APIENTRY * qglVertex4s )(GLshort x, GLshort y, GLshort z, GLshort w);
void ( APIENTRY * qglVertex4sv )(const GLshort *v);
void ( APIENTRY * qglVertexPointer )(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void ( APIENTRY * qglViewport )(GLint x, GLint y, GLsizei width, GLsizei height);

void ( APIENTRY * qglPointParameterfEXT)( GLenum param, GLfloat value );
void ( APIENTRY * qglPointParameterfvEXT)( GLenum param, const GLfloat *value );
void ( APIENTRY * qglColorTableEXT)( int, int, int, int, int, const void * );

void ( APIENTRY * qglLockArraysEXT) (int , int);
void ( APIENTRY * qglUnlockArraysEXT) (void);

void ( APIENTRY * qglMTexCoord2fSGIS)( GLenum, GLfloat, GLfloat );
void ( APIENTRY * qglSelectTextureSGIS)( GLenum );

/// BEATO Begin

void ( APIENTRY * qglDeleteBuffers ( GLsizei n, const GLuint *buffers );
PFNGLCREATEBUFFERSPROC               qglCreateBuffers;
PFNGLNAMEDBUFFERSTORAGEPROC          qglNamedBufferStorage;
PFNGLMAPNAMEDBUFFERRANGEPROC         qglMapNamedBufferRange;
PFNGLUNMAPNAMEDBUFFERPROC            qglUnmapNamedBuffer;
PFNGLCOPYNAMEDBUFFERSUBDATAPROC      qglCopyNamedBufferSubData;
PFNGLNAMEDBUFFERSUBDATAPROC          qglNamedBufferSubData;

PFNGLCREATEVERTEXARRAYSPROC          qglCreateVertexArrays;
PFNGLDELETEVERTEXARRAYSPROC          qglDeleteVertexArrays;
PFNGLBINDVERTEXARRAYPROC             qglBindVertexArray;
PFNGLENABLEVERTEXARRAYATTRIBPROC     qglEnableVertexArrayAttrib;
PFNGLDISABLEVERTEXARRAYATTRIBPROC    qglDisableVertexArrayAttrib;
PFNGLVERTEXATTRIBPOINTERPROC         qglVertexAttribPointer;
PFNGLVERTEXARRAYATTRIBBINDINGPROC    qglVertexArrayAttribBinding;
PFNGLVERTEXARRAYATTRIBFORMATPROC     qglVertexArrayAttribFormat;
PFNGLVERTEXARRAYELEMENTBUFFERPROC    qglVertexArrayElementBuffer;
PFNGLVERTEXARRAYVERTEXBUFFERPROC     qglVertexArrayVertexBuffer;
/// BEATO End

#ifdef _WIN32

int   ( WINAPI * qwglChoosePixelFormat )(HDC, CONST PIXELFORMATDESCRIPTOR *);
int   ( WINAPI * qwglDescribePixelFormat) (HDC, int, UINT, LPPIXELFORMATDESCRIPTOR);
int   ( WINAPI * qwglGetPixelFormat)(HDC);
BOOL  ( WINAPI * qwglSetPixelFormat)(HDC, int, CONST PIXELFORMATDESCRIPTOR *);
BOOL  ( WINAPI * qwglSwapBuffers)(HDC);

BOOL  ( WINAPI * qwglCopyContext)(HGLRC, HGLRC, UINT);
HGLRC ( WINAPI * qwglCreateContext)(HDC);
HGLRC ( WINAPI * qwglCreateLayerContext)(HDC, int);
BOOL  ( WINAPI * qwglDeleteContext)(HGLRC);
HGLRC ( WINAPI * qwglGetCurrentContext)(VOID);
HDC   ( WINAPI * qwglGetCurrentDC)(VOID);
PROC  ( WINAPI * qwglGetProcAddress)(LPCSTR);
BOOL  ( WINAPI * qwglMakeCurrent)(HDC, HGLRC);
BOOL  ( WINAPI * qwglShareLists)(HGLRC, HGLRC);
BOOL  ( WINAPI * qwglUseFontBitmaps)(HDC, DWORD, DWORD, DWORD);

BOOL  ( WINAPI * qwglUseFontOutlines)(HDC, DWORD, DWORD, DWORD, FLOAT,
                                           FLOAT, int, LPGLYPHMETRICSFLOAT);

BOOL ( WINAPI * qwglDescribeLayerPlane)(HDC, int, int, UINT,
                                            LPLAYERPLANEDESCRIPTOR);
int  ( WINAPI * qwglSetLayerPaletteEntries)(HDC, int, int, int,
                                                CONST COLORREF *);
int  ( WINAPI * qwglGetLayerPaletteEntries)(HDC, int, int, int,
                                                COLORREF *);
BOOL ( WINAPI * qwglRealizeLayerPalette)(HDC, int, BOOL);
BOOL ( WINAPI * qwglSwapLayerBuffers)(HDC, UINT);

BOOL ( WINAPI * qwglSwapIntervalEXT)( int interval );

BOOL ( WINAPI * qwglGetDeviceGammaRampEXT ) ( unsigned char *pRed, unsigned char *pGreen, unsigned char *pBlue );
BOOL ( WINAPI * qwglSetDeviceGammaRampEXT ) ( const unsigned char *pRed, const unsigned char *pGreen, const unsigned char *pBlue );

#endif

/*
** QGL_Init
**
** This is responsible for binding our qgl function pointers to 
** the appropriate GL stuff.  In Windows this means doing a 
** LoadLibrary and a bunch of calls to GetProcAddress.  On other
** operating systems we need to do the right thing, whatever that
** might be.
** 
*/
bool QGL_Init( const char *dllname )
{
	ri.GLimp_LoadLibary( dllname );

    // TODO: need define SDL load point
	qglAccum                     = ri.GLimp_GetProcAddress( "glAccum" );
	qglAlphaFunc                 = ri.GLimp_GetProcAddress( "glAlphaFunc" );
	qglAreTexturesResident       = ri.GLimp_GetProcAddress( "glAreTexturesResident" );
	qglArrayElement              = ri.GLimp_GetProcAddress( "glArrayElement" );
	qglBegin                     = ri.GLimp_GetProcAddress( "glBegin" );
	qglBindTexture               = ri.GLimp_GetProcAddress( "glBindTexture" );
	qglBitmap                    = ri.GLimp_GetProcAddress( "glBitmap" );
	qglBlendFunc                 = ri.GLimp_GetProcAddress( "glBlendFunc" );
	qglCallList                  = ri.GLimp_GetProcAddress( "glCallList" );
	qglCallLists                 = ri.GLimp_GetProcAddress( "glCallLists" );
	qglClear                     = ri.GLimp_GetProcAddress( "glClear" );
	qglClearAccum                = ri.GLimp_GetProcAddress( "glClearAccum" );
	qglClearColor                = ri.GLimp_GetProcAddress( "glClearColor" );
	qglClearDepth                = ri.GLimp_GetProcAddress( "glClearDepth" );
	qglClearIndex                = ri.GLimp_GetProcAddress( "glClearIndex" );
	qglClearStencil              = ri.GLimp_GetProcAddress( "glClearStencil" );
	qglClipPlane                 = ri.GLimp_GetProcAddress( "glClipPlane" );
	qglColor3b                   = ri.GLimp_GetProcAddress( "glColor3b" );
	qglColor3bv                  = ri.GLimp_GetProcAddress( "glColor3bv" );
	qglColor3d                   = ri.GLimp_GetProcAddress( "glColor3d" );
	qglColor3dv                  = ri.GLimp_GetProcAddress( "glColor3dv" );
	qglColor3f                   = ri.GLimp_GetProcAddress( "glColor3f" );
	qglColor3fv                  = ri.GLimp_GetProcAddress( "glColor3fv" );
	qglColor3i                   = ri.GLimp_GetProcAddress( "glColor3i" );
	qglColor3iv                  = ri.GLimp_GetProcAddress( "glColor3iv" );
	qglColor3s                   = ri.GLimp_GetProcAddress( "glColor3s" );
	qglColor3sv                  = ri.GLimp_GetProcAddress( "glColor3sv" );
	qglColor3ub                  = ri.GLimp_GetProcAddress( "glColor3ub" );
	qglColor3ubv                 = ri.GLimp_GetProcAddress( "glColor3ubv" );
	qglColor3ui                  = ri.GLimp_GetProcAddress( "glColor3ui" );
	qglColor3uiv                 = ri.GLimp_GetProcAddress( "glColor3uiv" );
	qglColor3us                  = ri.GLimp_GetProcAddress( "glColor3us" );
	qglColor3usv                 = ri.GLimp_GetProcAddress( "glColor3usv" );
	qglColor4b                   = ri.GLimp_GetProcAddress( "glColor4b" );
	qglColor4bv                  = ri.GLimp_GetProcAddress( "glColor4bv" );
	qglColor4d                   = ri.GLimp_GetProcAddress( "glColor4d" );
	qglColor4dv                  = ri.GLimp_GetProcAddress( "glColor4dv" );
	qglColor4f                   = ri.GLimp_GetProcAddress( "glColor4f" );
	qglColor4fv                  = ri.GLimp_GetProcAddress( "glColor4fv" );
	qglColor4i                   = ri.GLimp_GetProcAddress( "glColor4i" );
	qglColor4iv                  = ri.GLimp_GetProcAddress( "glColor4iv" );
	qglColor4s                   = ri.GLimp_GetProcAddress( "glColor4s" );
	qglColor4sv                  = ri.GLimp_GetProcAddress( "glColor4sv" );
	qglColor4ub                  = ri.GLimp_GetProcAddress( "glColor4ub" );
	qglColor4ubv                 = ri.GLimp_GetProcAddress( "glColor4ubv" );
	qglColor4ui                  = ri.GLimp_GetProcAddress( "glColor4ui" );
	qglColor4uiv                 = ri.GLimp_GetProcAddress( "glColor4uiv" );
	qglColor4us                  = ri.GLimp_GetProcAddress( "glColor4us" );
	qglColor4usv                 = ri.GLimp_GetProcAddress( "glColor4usv" );
	qglColorMask                 = ri.GLimp_GetProcAddress( "glColorMask" );
	qglColorMaterial             = ri.GLimp_GetProcAddress( "glColorMaterial" );
	qglColorPointer              = ri.GLimp_GetProcAddress( "glColorPointer" );
	qglCopyPixels                = ri.GLimp_GetProcAddress( "glCopyPixels" );
	qglCopyTexImage1D            = ri.GLimp_GetProcAddress( "glCopyTexImage1D" );
	qglCopyTexImage2D            = ri.GLimp_GetProcAddress( "glCopyTexImage2D" );
	qglCopyTexSubImage1D         = ri.GLimp_GetProcAddress( "glCopyTexSubImage1D" );
	qglCopyTexSubImage2D         = ri.GLimp_GetProcAddress( "glCopyTexSubImage2D" );
	qglCullFace                  = ri.GLimp_GetProcAddress( "glCullFace" );
	qglDeleteLists               = ri.GLimp_GetProcAddress( "glDeleteLists" );
	qglDeleteTextures            = ri.GLimp_GetProcAddress( "glDeleteTextures" );
	qglDepthFunc                 = ri.GLimp_GetProcAddress( "glDepthFunc" );
	qglDepthMask                 = ri.GLimp_GetProcAddress( "glDepthMask" );
	qglDepthRange                = ri.GLimp_GetProcAddress( "glDepthRange" );
	qglDisable                   = ri.GLimp_GetProcAddress( "glDisable" );
	qglDisableClientState        = ri.GLimp_GetProcAddress( "glDisableClientState" );
	qglDrawArrays                = ri.GLimp_GetProcAddress( "glDrawArrays" );
	qglDrawBuffer                = ri.GLimp_GetProcAddress( "glDrawBuffer" );
	qglDrawElements              = ri.GLimp_GetProcAddress( "glDrawElements" );
	qglDrawPixels                = ri.GLimp_GetProcAddress( "glDrawPixels" );
	qglEdgeFlag                  = ri.GLimp_GetProcAddress( "glEdgeFlag" );
	qglEdgeFlagPointer           = ri.GLimp_GetProcAddress( "glEdgeFlagPointer" );
	qglEdgeFlagv                 = ri.GLimp_GetProcAddress( "glEdgeFlagv" );
	qglEnable                    = 	ri.GLimp_GetProcAddress( "glEnable" );
	qglEnableClientState         = 	ri.GLimp_GetProcAddress( "glEnableClientState" );
	qglEnd                       = 	ri.GLimp_GetProcAddress( "glEnd" );
	qglEndList                   = 	ri.GLimp_GetProcAddress( "glEndList" );
	qglEvalCoord1d				 = 	ri.GLimp_GetProcAddress( "glEvalCoord1d" );
	qglEvalCoord1dv              = 	ri.GLimp_GetProcAddress( "glEvalCoord1dv" );
	qglEvalCoord1f               = 	ri.GLimp_GetProcAddress( "glEvalCoord1f" );
	qglEvalCoord1fv              = 	ri.GLimp_GetProcAddress( "glEvalCoord1fv" );
	qglEvalCoord2d               = 	ri.GLimp_GetProcAddress( "glEvalCoord2d" );
	qglEvalCoord2dv              = 	ri.GLimp_GetProcAddress( "glEvalCoord2dv" );
	qglEvalCoord2f               = 	ri.GLimp_GetProcAddress( "glEvalCoord2f" );
	qglEvalCoord2fv              = 	ri.GLimp_GetProcAddress( "glEvalCoord2fv" );
	qglEvalMesh1                 = 	ri.GLimp_GetProcAddress( "glEvalMesh1" );
	qglEvalMesh2                 = 	ri.GLimp_GetProcAddress( "glEvalMesh2" );
	qglEvalPoint1                = 	ri.GLimp_GetProcAddress( "glEvalPoint1" );
	qglEvalPoint2                = 	ri.GLimp_GetProcAddress( "glEvalPoint2" );
	qglFeedbackBuffer            = 	ri.GLimp_GetProcAddress( "glFeedbackBuffer" );
	qglFinish                    = 	ri.GLimp_GetProcAddress( "glFinish" );
	qglFlush                     = 	ri.GLimp_GetProcAddress( "glFlush" );
	qglFogf                      = 	ri.GLimp_GetProcAddress( "glFogf" );
	qglFogfv                     = 	ri.GLimp_GetProcAddress( "glFogfv" );
	qglFogi                      = 	ri.GLimp_GetProcAddress( "glFogi" );
	qglFogiv                     = 	ri.GLimp_GetProcAddress( "glFogiv" );
	qglFrontFace                 = 	ri.GLimp_GetProcAddress( "glFrontFace" );
	qglFrustum                   = 	ri.GLimp_GetProcAddress( "glFrustum" );
	qglGenLists                  = 	ri.GLimp_GetProcAddress( "glGenLists" );
	qglGenTextures               = 	ri.GLimp_GetProcAddress( "glGenTextures" );
	qglGetBooleanv               = 	ri.GLimp_GetProcAddress( "glGetBooleanv" );
	qglGetClipPlane              = 	ri.GLimp_GetProcAddress( "glGetClipPlane" );
	qglGetDoublev                = 	ri.GLimp_GetProcAddress( "glGetDoublev" );
	qglGetError                  = 	ri.GLimp_GetProcAddress( "glGetError" );
	qglGetFloatv                 = 	ri.GLimp_GetProcAddress( "glGetFloatv" );
	qglGetIntegerv               = 	ri.GLimp_GetProcAddress( "glGetIntegerv" );
	qglGetLightfv                = 	ri.GLimp_GetProcAddress( "glGetLightfv" );
	qglGetLightiv                = 	ri.GLimp_GetProcAddress( "glGetLightiv" );
	qglGetMapdv                  = 	ri.GLimp_GetProcAddress( "glGetMapdv" );
	qglGetMapfv                  = 	ri.GLimp_GetProcAddress( "glGetMapfv" );
	qglGetMapiv                  = 	ri.GLimp_GetProcAddress( "glGetMapiv" );
	qglGetMaterialfv             = 	ri.GLimp_GetProcAddress( "glGetMaterialfv" );
	qglGetMaterialiv             = 	ri.GLimp_GetProcAddress( "glGetMaterialiv" );
	qglGetPixelMapfv             = 	ri.GLimp_GetProcAddress( "glGetPixelMapfv" );
	qglGetPixelMapuiv            = 	ri.GLimp_GetProcAddress( "glGetPixelMapuiv" );
	qglGetPixelMapusv            = 	ri.GLimp_GetProcAddress( "glGetPixelMapusv" );
	qglGetPointerv               = 	ri.GLimp_GetProcAddress( "glGetPointerv" );
	qglGetPolygonStipple         = 	ri.GLimp_GetProcAddress( "glGetPolygonStipple" );
	qglGetString                 = 	ri.GLimp_GetProcAddress( "glGetString" );
	qglGetTexEnvfv               = 	ri.GLimp_GetProcAddress( "glGetTexEnvfv" );
	qglGetTexEnviv               = 	ri.GLimp_GetProcAddress( "glGetTexEnviv" );
	qglGetTexGendv               = 	ri.GLimp_GetProcAddress( "glGetTexGendv" );
	qglGetTexGenfv               = 	ri.GLimp_GetProcAddress( "glGetTexGenfv" );
	qglGetTexGeniv               = 	ri.GLimp_GetProcAddress( "glGetTexGeniv" );
	qglGetTexImage               = 	ri.GLimp_GetProcAddress( "glGetTexImage" );
//	qglGetTexLevelParameterfv    = 	dllGetTexLevelParameterfv    = glGetLevelParameterfv;
//	qglGetTexLevelParameteriv    = 	dllGetTexLevelParameteriv    = glGetLevelParameteriv;
	qglGetTexParameterfv         = 	ri.GLimp_GetProcAddress( "glGetTexParameterfv" );
	qglGetTexParameteriv         = 	ri.GLimp_GetProcAddress( "glGetTexParameteriv" );
	qglHint                      = 	ri.GLimp_GetProcAddress( "glHint" );
	qglIndexMask                 = 	ri.GLimp_GetProcAddress( "glIndexMask" );
	qglIndexPointer              = 	ri.GLimp_GetProcAddress( "glIndexPointer" );
	qglIndexd                    = 	ri.GLimp_GetProcAddress( "glIndexd" );
	qglIndexdv                   = 	ri.GLimp_GetProcAddress( "glIndexdv" );
	qglIndexf                    = 	ri.GLimp_GetProcAddress( "glIndexf" );
	qglIndexfv                   = 	ri.GLimp_GetProcAddress( "glIndexfv" );
	qglIndexi                    = 	ri.GLimp_GetProcAddress( "glIndexi" );
	qglIndexiv                   = 	ri.GLimp_GetProcAddress( "glIndexiv" );
	qglIndexs                    = 	ri.GLimp_GetProcAddress( "glIndexs" );
	qglIndexsv                   = 	ri.GLimp_GetProcAddress( "glIndexsv" );
	qglIndexub                   = 	ri.GLimp_GetProcAddress( "glIndexub" );
	qglIndexubv                  = 	ri.GLimp_GetProcAddress( "glIndexubv" );
	qglInitNames                 = 	ri.GLimp_GetProcAddress( "glInitNames" );
	qglInterleavedArrays         = 	ri.GLimp_GetProcAddress( "glInterleavedArrays" );
	qglIsEnabled                 = 	ri.GLimp_GetProcAddress( "glIsEnabled" );
	qglIsList                    = 	ri.GLimp_GetProcAddress( "glIsList" );
	qglIsTexture                 = 	ri.GLimp_GetProcAddress( "glIsTexture" );
	qglLightModelf               = 	ri.GLimp_GetProcAddress( "glLightModelf" );
	qglLightModelfv              = 	ri.GLimp_GetProcAddress( "glLightModelfv" );
	qglLightModeli               = 	ri.GLimp_GetProcAddress( "glLightModeli" );
	qglLightModeliv              = 	ri.GLimp_GetProcAddress( "glLightModeliv" );
	qglLightf                    = 	ri.GLimp_GetProcAddress( "glLightf" );
	qglLightfv                   = 	ri.GLimp_GetProcAddress( "glLightfv" );
	qglLighti                    = 	ri.GLimp_GetProcAddress( "glLighti" );
	qglLightiv                   = 	ri.GLimp_GetProcAddress( "glLightiv" );
	qglLineStipple               = 	ri.GLimp_GetProcAddress( "glLineStipple" );
	qglLineWidth                 = 	ri.GLimp_GetProcAddress( "glLineWidth" );
	qglListBase                  = 	ri.GLimp_GetProcAddress( "glListBase" );
	qglLoadIdentity              = 	ri.GLimp_GetProcAddress( "glLoadIdentity" );
	qglLoadMatrixd               = 	ri.GLimp_GetProcAddress( "glLoadMatrixd" );
	qglLoadMatrixf               = 	ri.GLimp_GetProcAddress( "glLoadMatrixf" );
	qglLoadName                  = 	ri.GLimp_GetProcAddress( "glLoadName" );
	qglLogicOp                   = 	ri.GLimp_GetProcAddress( "glLogicOp" );
	qglMap1d                     = 	ri.GLimp_GetProcAddress( "glMap1d" );
	qglMap1f                     = 	ri.GLimp_GetProcAddress( "glMap1f" );
	qglMap2d                     = 	ri.GLimp_GetProcAddress( "glMap2d" );
	qglMap2f                     = 	ri.GLimp_GetProcAddress( "glMap2f" );
	qglMapGrid1d                 = 	ri.GLimp_GetProcAddress( "glMapGrid1d" );
	qglMapGrid1f                 = 	ri.GLimp_GetProcAddress( "glMapGrid1f" );
	qglMapGrid2d                 = 	ri.GLimp_GetProcAddress( "glMapGrid2d" );
	qglMapGrid2f                 = 	ri.GLimp_GetProcAddress( "glMapGrid2f" );
	qglMaterialf                 = 	ri.GLimp_GetProcAddress( "glMaterialf" );
	qglMaterialfv                = 	ri.GLimp_GetProcAddress( "glMaterialfv" );
	qglMateriali                 = 	ri.GLimp_GetProcAddress( "glMateriali" );
	qglMaterialiv                = 	ri.GLimp_GetProcAddress( "glMaterialiv" );
	qglMatrixMode                = 	ri.GLimp_GetProcAddress( "glMatrixMode" );
	qglMultMatrixd               = 	ri.GLimp_GetProcAddress( "glMultMatrixd" );
	qglMultMatrixf               = 	ri.GLimp_GetProcAddress( "glMultMatrixf" );
	qglNewList                   = 	ri.GLimp_GetProcAddress( "glNewList" );
	qglNormal3b                  = 	ri.GLimp_GetProcAddress( "glNormal3b" );
	qglNormal3bv                 = 	ri.GLimp_GetProcAddress( "glNormal3bv" );
	qglNormal3d                  = 	ri.GLimp_GetProcAddress( "glNormal3d" );
	qglNormal3dv                 = 	ri.GLimp_GetProcAddress( "glNormal3dv" );
	qglNormal3f                  = 	ri.GLimp_GetProcAddress( "glNormal3f" );
	qglNormal3fv                 = 	ri.GLimp_GetProcAddress( "glNormal3fv" );
	qglNormal3i                  = 	ri.GLimp_GetProcAddress( "glNormal3i" );
	qglNormal3iv                 = 	ri.GLimp_GetProcAddress( "glNormal3iv" );
	qglNormal3s                  = 	ri.GLimp_GetProcAddress( "glNormal3s" );
	qglNormal3sv                 = 	ri.GLimp_GetProcAddress( "glNormal3sv" );
	qglNormalPointer             = 	ri.GLimp_GetProcAddress( "glNormalPointer" );
	qglOrtho                     = 	ri.GLimp_GetProcAddress( "glOrtho" );
	qglPassThrough               = 	ri.GLimp_GetProcAddress( "glPassThrough" );
	qglPixelMapfv                = 	ri.GLimp_GetProcAddress( "glPixelMapfv" );
	qglPixelMapuiv               = 	ri.GLimp_GetProcAddress( "glPixelMapuiv" );
	qglPixelMapusv               = 	ri.GLimp_GetProcAddress( "glPixelMapusv" );
	qglPixelStoref               = 	ri.GLimp_GetProcAddress( "glPixelStoref" );
	qglPixelStorei               = 	ri.GLimp_GetProcAddress( "glPixelStorei" );
	qglPixelTransferf            = 	ri.GLimp_GetProcAddress( "glPixelTransferf" );
	qglPixelTransferi            = 	ri.GLimp_GetProcAddress( "glPixelTransferi" );
	qglPixelZoom                 = 	ri.GLimp_GetProcAddress( "glPixelZoom" );
	qglPointSize                 = 	ri.GLimp_GetProcAddress( "glPointSize" );
	qglPolygonMode               = 	ri.GLimp_GetProcAddress( "glPolygonMode" );
	qglPolygonOffset             = 	ri.GLimp_GetProcAddress( "glPolygonOffset" );
	qglPolygonStipple            = 	ri.GLimp_GetProcAddress( "glPolygonStipple" );
	qglPopAttrib                 = 	ri.GLimp_GetProcAddress( "glPopAttrib" );
	qglPopClientAttrib           = 	ri.GLimp_GetProcAddress( "glPopClientAttrib" );
	qglPopMatrix                 = 	ri.GLimp_GetProcAddress( "glPopMatrix" );
	qglPopName                   = 	ri.GLimp_GetProcAddress( "glPopName" );
	qglPrioritizeTextures        = 	ri.GLimp_GetProcAddress( "glPrioritizeTextures" );
	qglPushAttrib                = 	ri.GLimp_GetProcAddress( "glPushAttrib" );
	qglPushClientAttrib          = 	ri.GLimp_GetProcAddress( "glPushClientAttrib" );
	qglPushMatrix                = 	ri.GLimp_GetProcAddress( "glPushMatrix" );
	qglPushName                  = 	ri.GLimp_GetProcAddress( "glPushName" );
	qglRasterPos2d               = 	ri.GLimp_GetProcAddress( "glRasterPos2d" );
	qglRasterPos2dv              = 	ri.GLimp_GetProcAddress( "glRasterPos2dv" );
	qglRasterPos2f               = 	ri.GLimp_GetProcAddress( "glRasterPos2f" );
	qglRasterPos2fv              = 	ri.GLimp_GetProcAddress( "glRasterPos2fv" );
	qglRasterPos2i               = 	ri.GLimp_GetProcAddress( "glRasterPos2i" );
	qglRasterPos2iv              = 	ri.GLimp_GetProcAddress( "glRasterPos2iv" );
	qglRasterPos2s               = 	ri.GLimp_GetProcAddress( "glRasterPos2s" );
	qglRasterPos2sv              = 	ri.GLimp_GetProcAddress( "glRasterPos2sv" );
	qglRasterPos3d               = 	ri.GLimp_GetProcAddress( "glRasterPos3d" );
	qglRasterPos3dv              = 	ri.GLimp_GetProcAddress( "glRasterPos3dv" );
	qglRasterPos3f               = 	ri.GLimp_GetProcAddress( "glRasterPos3f" );
	qglRasterPos3fv              = 	ri.GLimp_GetProcAddress( "glRasterPos3fv" );
	qglRasterPos3i               = 	ri.GLimp_GetProcAddress( "glRasterPos3i" );
	qglRasterPos3iv              = 	ri.GLimp_GetProcAddress( "glRasterPos3iv" );
	qglRasterPos3s               = 	ri.GLimp_GetProcAddress( "glRasterPos3s" );
	qglRasterPos3sv              = 	ri.GLimp_GetProcAddress( "glRasterPos3sv" );
	qglRasterPos4d               = 	ri.GLimp_GetProcAddress( "glRasterPos4d" );
	qglRasterPos4dv              = 	ri.GLimp_GetProcAddress( "glRasterPos4dv" );
	qglRasterPos4f               = 	ri.GLimp_GetProcAddress( "glRasterPos4f" );
	qglRasterPos4fv              = 	ri.GLimp_GetProcAddress( "glRasterPos4fv" );
	qglRasterPos4i               = 	ri.GLimp_GetProcAddress( "glRasterPos4i" );
	qglRasterPos4iv              = 	ri.GLimp_GetProcAddress( "glRasterPos4iv" );
	qglRasterPos4s               = 	ri.GLimp_GetProcAddress( "glRasterPos4s" );
	qglRasterPos4sv              = 	ri.GLimp_GetProcAddress( "glRasterPos4sv" );
	qglReadBuffer                = 	ri.GLimp_GetProcAddress( "glReadBuffer" );
	qglReadPixels                = 	ri.GLimp_GetProcAddress( "glReadPixels" );
	qglRectd                     = 	ri.GLimp_GetProcAddress( "glRectd" );
	qglRectdv                    = 	ri.GLimp_GetProcAddress( "glRectdv" );
	qglRectf                     = 	ri.GLimp_GetProcAddress( "glRectf" );
	qglRectfv                    = 	ri.GLimp_GetProcAddress( "glRectfv" );
	qglRecti                     = 	ri.GLimp_GetProcAddress( "glRecti" );
	qglRectiv                    = 	ri.GLimp_GetProcAddress( "glRectiv" );
	qglRects                     = 	ri.GLimp_GetProcAddress( "glRects" );
	qglRectsv                    = 	ri.GLimp_GetProcAddress( "glRectsv" );
	qglRenderMode                = 	ri.GLimp_GetProcAddress( "glRenderMode" );
	qglRotated                   = 	ri.GLimp_GetProcAddress( "glRotated" );
	qglRotatef                   = 	ri.GLimp_GetProcAddress( "glRotatef" );
	qglScaled                    = 	ri.GLimp_GetProcAddress( "glScaled" );
	qglScalef                    = 	ri.GLimp_GetProcAddress( "glScalef" );
	qglScissor                   = 	ri.GLimp_GetProcAddress( "glScissor" );
	qglSelectBuffer              = 	ri.GLimp_GetProcAddress( "glSelectBuffer" );
	qglShadeModel                = 	ri.GLimp_GetProcAddress( "glShadeModel" );
	qglStencilFunc               = 	ri.GLimp_GetProcAddress( "glStencilFunc" );
	qglStencilMask               = 	ri.GLimp_GetProcAddress( "glStencilMask" );
	qglStencilOp                 = 	ri.GLimp_GetProcAddress( "glStencilOp" );
	qglTexCoord1d                = 	ri.GLimp_GetProcAddress( "glTexCoord1d" );
	qglTexCoord1dv               = 	ri.GLimp_GetProcAddress( "glTexCoord1dv" );
	qglTexCoord1f                = 	ri.GLimp_GetProcAddress( "glTexCoord1f" );
	qglTexCoord1fv               = 	ri.GLimp_GetProcAddress( "glTexCoord1fv" );
	qglTexCoord1i                = 	ri.GLimp_GetProcAddress( "glTexCoord1i" );
	qglTexCoord1iv               = 	ri.GLimp_GetProcAddress( "glTexCoord1iv" );
	qglTexCoord1s                = 	ri.GLimp_GetProcAddress( "glTexCoord1s" );
	qglTexCoord1sv               = 	ri.GLimp_GetProcAddress( "glTexCoord1sv" );
	qglTexCoord2d                = 	ri.GLimp_GetProcAddress( "glTexCoord2d" );
	qglTexCoord2dv               = 	ri.GLimp_GetProcAddress( "glTexCoord2dv" );
	qglTexCoord2f                = 	ri.GLimp_GetProcAddress( "glTexCoord2f" );
	qglTexCoord2fv               = 	ri.GLimp_GetProcAddress( "glTexCoord2fv" );
	qglTexCoord2i                = 	ri.GLimp_GetProcAddress( "glTexCoord2i" );
	qglTexCoord2iv               = 	ri.GLimp_GetProcAddress( "glTexCoord2iv" );
	qglTexCoord2s                = 	ri.GLimp_GetProcAddress( "glTexCoord2s" );
	qglTexCoord2sv               = 	ri.GLimp_GetProcAddress( "glTexCoord2sv" );
	qglTexCoord3d                = 	ri.GLimp_GetProcAddress( "glTexCoord3d" );
	qglTexCoord3dv               = 	ri.GLimp_GetProcAddress( "glTexCoord3dv" );
	qglTexCoord3f                = 	ri.GLimp_GetProcAddress( "glTexCoord3f" );
	qglTexCoord3fv               = 	ri.GLimp_GetProcAddress( "glTexCoord3fv" );
	qglTexCoord3i                = 	ri.GLimp_GetProcAddress( "glTexCoord3i" );
	qglTexCoord3iv               = 	ri.GLimp_GetProcAddress( "glTexCoord3iv" );
	qglTexCoord3s                = 	ri.GLimp_GetProcAddress( "glTexCoord3s" );
	qglTexCoord3sv               = 	ri.GLimp_GetProcAddress( "glTexCoord3sv" );
	qglTexCoord4d                = 	ri.GLimp_GetProcAddress( "glTexCoord4d" );
	qglTexCoord4dv               = 	ri.GLimp_GetProcAddress( "glTexCoord4dv" );
	qglTexCoord4f                = 	ri.GLimp_GetProcAddress( "glTexCoord4f" );
	qglTexCoord4fv               = 	ri.GLimp_GetProcAddress( "glTexCoord4fv" );
	qglTexCoord4i                = 	ri.GLimp_GetProcAddress( "glTexCoord4i" );
	qglTexCoord4iv               = 	ri.GLimp_GetProcAddress( "glTexCoord4iv" );
	qglTexCoord4s                = 	ri.GLimp_GetProcAddress( "glTexCoord4s" );
	qglTexCoord4sv               = 	ri.GLimp_GetProcAddress( "glTexCoord4sv" );
	qglTexCoordPointer           = 	ri.GLimp_GetProcAddress( "glTexCoordPointer" );
	qglTexEnvf                   = 	ri.GLimp_GetProcAddress( "glTexEnvf" );
	qglTexEnvfv                  = 	ri.GLimp_GetProcAddress( "glTexEnvfv" );
	qglTexEnvi                   = 	ri.GLimp_GetProcAddress( "glTexEnvi" );
	qglTexEnviv                  = 	ri.GLimp_GetProcAddress( "glTexEnviv" );
	qglTexGend                   = 	ri.GLimp_GetProcAddress( "glTexGend" );
	qglTexGendv                  = 	ri.GLimp_GetProcAddress( "glTexGendv" );
	qglTexGenf                   = 	ri.GLimp_GetProcAddress( "glTexGenf" );
	qglTexGenfv                  = 	ri.GLimp_GetProcAddress( "glTexGenfv" );
	qglTexGeni                   = 	ri.GLimp_GetProcAddress( "glTexGeni" );
	qglTexGeniv                  = 	ri.GLimp_GetProcAddress( "glTexGeniv" );
	qglTexImage1D                = 	ri.GLimp_GetProcAddress( "glTexImage1D" );
	qglTexImage2D                = 	ri.GLimp_GetProcAddress( "glTexImage2D" );
	qglTexParameterf             = 	ri.GLimp_GetProcAddress( "glTexParameterf" );
	qglTexParameterfv            = 	ri.GLimp_GetProcAddress( "glTexParameterfv" );
	qglTexParameteri             = 	ri.GLimp_GetProcAddress( "glTexParameteri" );
	qglTexParameteriv            = 	ri.GLimp_GetProcAddress( "glTexParameteriv" );
	qglTexSubImage1D             = 	ri.GLimp_GetProcAddress( "glTexSubImage1D" );
	qglTexSubImage2D             = 	ri.GLimp_GetProcAddress( "glTexSubImage2D" );
	qglTranslated                = 	ri.GLimp_GetProcAddress( "glTranslated" );
	qglTranslatef                = 	ri.GLimp_GetProcAddress( "glTranslatef" );
	qglVertex2d                  = 	ri.GLimp_GetProcAddress( "glVertex2d" );
	qglVertex2dv                 = 	ri.GLimp_GetProcAddress( "glVertex2dv" );
	qglVertex2f                  = 	ri.GLimp_GetProcAddress( "glVertex2f" );
	qglVertex2fv                 = 	ri.GLimp_GetProcAddress( "glVertex2fv" );
	qglVertex2i                  = 	ri.GLimp_GetProcAddress( "glVertex2i" );
	qglVertex2iv                 = 	ri.GLimp_GetProcAddress( "glVertex2iv" );
	qglVertex2s                  = 	ri.GLimp_GetProcAddress( "glVertex2s" );
	qglVertex2sv                 = 	ri.GLimp_GetProcAddress( "glVertex2sv" );
	qglVertex3d                  = 	ri.GLimp_GetProcAddress( "glVertex3d" );
	qglVertex3dv                 = 	ri.GLimp_GetProcAddress( "glVertex3dv" );
	qglVertex3f                  = 	ri.GLimp_GetProcAddress( "glVertex3f" );
	qglVertex3fv                 = 	ri.GLimp_GetProcAddress( "glVertex3fv" );
	qglVertex3i                  = 	ri.GLimp_GetProcAddress( "glVertex3i" );
	qglVertex3iv                 = 	ri.GLimp_GetProcAddress( "glVertex3iv" );
	qglVertex3s                  = 	ri.GLimp_GetProcAddress( "glVertex3s" );
	qglVertex3sv                 = 	ri.GLimp_GetProcAddress( "glVertex3sv" );
	qglVertex4d                  = 	ri.GLimp_GetProcAddress( "glVertex4d" );
	qglVertex4dv                 = 	ri.GLimp_GetProcAddress( "glVertex4dv" );
	qglVertex4f                  = 	ri.GLimp_GetProcAddress( "glVertex4f" );
	qglVertex4fv                 = 	ri.GLimp_GetProcAddress( "glVertex4fv" );
	qglVertex4i                  = 	ri.GLimp_GetProcAddress( "glVertex4i" );
	qglVertex4iv                 = 	ri.GLimp_GetProcAddress( "glVertex4iv" );
	qglVertex4s                  = 	ri.GLimp_GetProcAddress( "glVertex4s" );
	qglVertex4sv                 = 	ri.GLimp_GetProcAddress( "glVertex4sv" );
	qglVertexPointer             = 	ri.GLimp_GetProcAddress( "glVertexPointer" );
	qglViewport                  = 	ri.GLimp_GetProcAddress( "glViewport" );

	qglDeleteBuffers			= ri.GLimp_GetProcAddress( "qglDeleteBuffers" );
	qglCreateBuffers 			= ri.GLimp_GetProcAddress( "glCreateBuffers" );
	qglNamedBufferStorage 		= ri.GLimp_GetProcAddress( "glNamedBufferStorage" );
	qglMapNamedBufferRange 		= ri.GLimp_GetProcAddress( "glMapNamedBufferRange" );
	qglUnmapNamedBuffer 		= ri.GLimp_GetProcAddress( "glUnmapNamedBuffer" );
	qglCopyNamedBufferSubData 	= ri.GLimp_GetProcAddress( "glCopyNamedBufferSubData" );
	qglNamedBufferSubData 		= ri.GLimp_GetProcAddress( "glNamedBufferSubData" );

	qglCreateVertexArrays 		= ri.GLimp_GetProcAddress( "glCreateVertexArrays" );
	qglDeleteVertexArrays 		= ri.GLimp_GetProcAddress( "glDeleteVertexArrays" );
	qglBindVertexArray 			= ri.GLimp_GetProcAddress( "glBindVertexArray" );
	qglEnableVertexArrayAttrib 	= ri.GLimp_GetProcAddress( "glEnableVertexArrayAttrib" );
	qglDisableVertexArrayAttrib = ri.GLimp_GetProcAddress( "glDisableVertexArrayAttrib" );
	qglVertexAttribPointer 		= ri.GLimp_GetProcAddress( "glVertexAttribPointer" );
	qglVertexArrayAttribBinding	= ri.GLimp_GetProcAddress( "glVertexArrayAttribBinding" );
	qglVertexArrayAttribFormat 	= ri.GLimp_GetProcAddress( "glVertexArrayAttribFormat" );
	qglVertexArrayElementBuffer = ri.GLimp_GetProcAddress( "glVertexArrayElementBuffer" );
	qglVertexArrayVertexBuffer 	= ri.GLimp_GetProcAddress( "glVertexArrayVertexBuffer" );

	qglPointParameterfEXT = 0;
	qglPointParameterfvEXT = 0;
	qglColorTableEXT = 0;
	qglSelectTextureSGIS = 0;
	qglMTexCoord2fSGIS = 0;

	return true;
}

/*
** QGL_Shutdown
**
** Unloads the specified DLL then nulls out all the proc pointers.
*/
void QGL_Shutdown( void )
{
	qglAccum                     = NULL;
	qglAlphaFunc                 = NULL;
	qglAreTexturesResident       = NULL;
	qglArrayElement              = NULL;
	qglBegin                     = NULL;
	qglBindTexture               = NULL;
	qglBitmap                    = NULL;
	qglBlendFunc                 = NULL;
	qglCallList                  = NULL;
	qglCallLists                 = NULL;
	qglClear                     = NULL;
	qglClearAccum                = NULL;
	qglClearColor                = NULL;
	qglClearDepth                = NULL;
	qglClearIndex                = NULL;
	qglClearStencil              = NULL;
	qglClipPlane                 = NULL;
	qglColor3b                   = NULL;
	qglColor3bv                  = NULL;
	qglColor3d                   = NULL;
	qglColor3dv                  = NULL;
	qglColor3f                   = NULL;
	qglColor3fv                  = NULL;
	qglColor3i                   = NULL;
	qglColor3iv                  = NULL;
	qglColor3s                   = NULL;
	qglColor3sv                  = NULL;
	qglColor3ub                  = NULL;
	qglColor3ubv                 = NULL;
	qglColor3ui                  = NULL;
	qglColor3uiv                 = NULL;
	qglColor3us                  = NULL;
	qglColor3usv                 = NULL;
	qglColor4b                   = NULL;
	qglColor4bv                  = NULL;
	qglColor4d                   = NULL;
	qglColor4dv                  = NULL;
	qglColor4f                   = NULL;
	qglColor4fv                  = NULL;
	qglColor4i                   = NULL;
	qglColor4iv                  = NULL;
	qglColor4s                   = NULL;
	qglColor4sv                  = NULL;
	qglColor4ub                  = NULL;
	qglColor4ubv                 = NULL;
	qglColor4ui                  = NULL;
	qglColor4uiv                 = NULL;
	qglColor4us                  = NULL;
	qglColor4usv                 = NULL;
	qglColorMask                 = NULL;
	qglColorMaterial             = NULL;
	qglColorPointer              = NULL;
	qglCopyPixels                = NULL;
	qglCopyTexImage1D            = NULL;
	qglCopyTexImage2D            = NULL;
	qglCopyTexSubImage1D         = NULL;
	qglCopyTexSubImage2D         = NULL;
	qglCullFace                  = NULL;
	qglDeleteLists               = NULL;
	qglDeleteTextures            = NULL;
	qglDepthFunc                 = NULL;
	qglDepthMask                 = NULL;
	qglDepthRange                = NULL;
	qglDisable                   = NULL;
	qglDisableClientState        = NULL;
	qglDrawArrays                = NULL;
	qglDrawBuffer                = NULL;
	qglDrawElements              = NULL;
	qglDrawPixels                = NULL;
	qglEdgeFlag                  = NULL;
	qglEdgeFlagPointer           = NULL;
	qglEdgeFlagv                 = NULL;
	qglEnable                    = NULL;
	qglEnableClientState         = NULL;
	qglEnd                       = NULL;
	qglEndList                   = NULL;
	qglEvalCoord1d               = NULL;
	qglEvalCoord1dv              = NULL;
	qglEvalCoord1f               = NULL;
	qglEvalCoord1fv              = NULL;
	qglEvalCoord2d               = NULL;
	qglEvalCoord2dv              = NULL;
	qglEvalCoord2f               = NULL;
	qglEvalCoord2fv              = NULL;
	qglEvalMesh1                 = NULL;
	qglEvalMesh2                 = NULL;
	qglEvalPoint1                = NULL;
	qglEvalPoint2                = NULL;
	qglFeedbackBuffer            = NULL;
	qglFinish                    = NULL;
	qglFlush                     = NULL;
	qglFogf                      = NULL;
	qglFogfv                     = NULL;
	qglFogi                      = NULL;
	qglFogiv                     = NULL;
	qglFrontFace                 = NULL;
	qglFrustum                   = NULL;
	qglGenLists                  = NULL;
	qglGenTextures               = NULL;
	qglGetBooleanv               = NULL;
	qglGetClipPlane              = NULL;
	qglGetDoublev                = NULL;
	qglGetError                  = NULL;
	qglGetFloatv                 = NULL;
	qglGetIntegerv               = NULL;
	qglGetLightfv                = NULL;
	qglGetLightiv                = NULL;
	qglGetMapdv                  = NULL;
	qglGetMapfv                  = NULL;
	qglGetMapiv                  = NULL;
	qglGetMaterialfv             = NULL;
	qglGetMaterialiv             = NULL;
	qglGetPixelMapfv             = NULL;
	qglGetPixelMapuiv            = NULL;
	qglGetPixelMapusv            = NULL;
	qglGetPointerv               = NULL;
	qglGetPolygonStipple         = NULL;
	qglGetString                 = NULL;
	qglGetTexEnvfv               = NULL;
	qglGetTexEnviv               = NULL;
	qglGetTexGendv               = NULL;
	qglGetTexGenfv               = NULL;
	qglGetTexGeniv               = NULL;
	qglGetTexImage               = NULL;
	qglGetTexLevelParameterfv    = NULL;
	qglGetTexLevelParameteriv    = NULL;
	qglGetTexParameterfv         = NULL;
	qglGetTexParameteriv         = NULL;
	qglHint                      = NULL;
	qglIndexMask                 = NULL;
	qglIndexPointer              = NULL;
	qglIndexd                    = NULL;
	qglIndexdv                   = NULL;
	qglIndexf                    = NULL;
	qglIndexfv                   = NULL;
	qglIndexi                    = NULL;
	qglIndexiv                   = NULL;
	qglIndexs                    = NULL;
	qglIndexsv                   = NULL;
	qglIndexub                   = NULL;
	qglIndexubv                  = NULL;
	qglInitNames                 = NULL;
	qglInterleavedArrays         = NULL;
	qglIsEnabled                 = NULL;
	qglIsList                    = NULL;
	qglIsTexture                 = NULL;
	qglLightModelf               = NULL;
	qglLightModelfv              = NULL;
	qglLightModeli               = NULL;
	qglLightModeliv              = NULL;
	qglLightf                    = NULL;
	qglLightfv                   = NULL;
	qglLighti                    = NULL;
	qglLightiv                   = NULL;
	qglLineStipple               = NULL;
	qglLineWidth                 = NULL;
	qglListBase                  = NULL;
	qglLoadIdentity              = NULL;
	qglLoadMatrixd               = NULL;
	qglLoadMatrixf               = NULL;
	qglLoadName                  = NULL;
	qglLogicOp                   = NULL;
	qglMap1d                     = NULL;
	qglMap1f                     = NULL;
	qglMap2d                     = NULL;
	qglMap2f                     = NULL;
	qglMapGrid1d                 = NULL;
	qglMapGrid1f                 = NULL;
	qglMapGrid2d                 = NULL;
	qglMapGrid2f                 = NULL;
	qglMaterialf                 = NULL;
	qglMaterialfv                = NULL;
	qglMateriali                 = NULL;
	qglMaterialiv                = NULL;
	qglMatrixMode                = NULL;
	qglMultMatrixd               = NULL;
	qglMultMatrixf               = NULL;
	qglNewList                   = NULL;
	qglNormal3b                  = NULL;
	qglNormal3bv                 = NULL;
	qglNormal3d                  = NULL;
	qglNormal3dv                 = NULL;
	qglNormal3f                  = NULL;
	qglNormal3fv                 = NULL;
	qglNormal3i                  = NULL;
	qglNormal3iv                 = NULL;
	qglNormal3s                  = NULL;
	qglNormal3sv                 = NULL;
	qglNormalPointer             = NULL;
	qglOrtho                     = NULL;
	qglPassThrough               = NULL;
	qglPixelMapfv                = NULL;
	qglPixelMapuiv               = NULL;
	qglPixelMapusv               = NULL;
	qglPixelStoref               = NULL;
	qglPixelStorei               = NULL;
	qglPixelTransferf            = NULL;
	qglPixelTransferi            = NULL;
	qglPixelZoom                 = NULL;
	qglPointSize                 = NULL;
	qglPolygonMode               = NULL;
	qglPolygonOffset             = NULL;
	qglPolygonStipple            = NULL;
	qglPopAttrib                 = NULL;
	qglPopClientAttrib           = NULL;
	qglPopMatrix                 = NULL;
	qglPopName                   = NULL;
	qglPrioritizeTextures        = NULL;
	qglPushAttrib                = NULL;
	qglPushClientAttrib          = NULL;
	qglPushMatrix                = NULL;
	qglPushName                  = NULL;
	qglRasterPos2d               = NULL;
	qglRasterPos2dv              = NULL;
	qglRasterPos2f               = NULL;
	qglRasterPos2fv              = NULL;
	qglRasterPos2i               = NULL;
	qglRasterPos2iv              = NULL;
	qglRasterPos2s               = NULL;
	qglRasterPos2sv              = NULL;
	qglRasterPos3d               = NULL;
	qglRasterPos3dv              = NULL;
	qglRasterPos3f               = NULL;
	qglRasterPos3fv              = NULL;
	qglRasterPos3i               = NULL;
	qglRasterPos3iv              = NULL;
	qglRasterPos3s               = NULL;
	qglRasterPos3sv              = NULL;
	qglRasterPos4d               = NULL;
	qglRasterPos4dv              = NULL;
	qglRasterPos4f               = NULL;
	qglRasterPos4fv              = NULL;
	qglRasterPos4i               = NULL;
	qglRasterPos4iv              = NULL;
	qglRasterPos4s               = NULL;
	qglRasterPos4sv              = NULL;
	qglReadBuffer                = NULL;
	qglReadPixels                = NULL;
	qglRectd                     = NULL;
	qglRectdv                    = NULL;
	qglRectf                     = NULL;
	qglRectfv                    = NULL;
	qglRecti                     = NULL;
	qglRectiv                    = NULL;
	qglRects                     = NULL;
	qglRectsv                    = NULL;
	qglRenderMode                = NULL;
	qglRotated                   = NULL;
	qglRotatef                   = NULL;
	qglScaled                    = NULL;
	qglScalef                    = NULL;
	qglScissor                   = NULL;
	qglSelectBuffer              = NULL;
	qglShadeModel                = NULL;
	qglStencilFunc               = NULL;
	qglStencilMask               = NULL;
	qglStencilOp                 = NULL;
	qglTexCoord1d                = NULL;
	qglTexCoord1dv               = NULL;
	qglTexCoord1f                = NULL;
	qglTexCoord1fv               = NULL;
	qglTexCoord1i                = NULL;
	qglTexCoord1iv               = NULL;
	qglTexCoord1s                = NULL;
	qglTexCoord1sv               = NULL;
	qglTexCoord2d                = NULL;
	qglTexCoord2dv               = NULL;
	qglTexCoord2f                = NULL;
	qglTexCoord2fv               = NULL;
	qglTexCoord2i                = NULL;
	qglTexCoord2iv               = NULL;
	qglTexCoord2s                = NULL;
	qglTexCoord2sv               = NULL;
	qglTexCoord3d                = NULL;
	qglTexCoord3dv               = NULL;
	qglTexCoord3f                = NULL;
	qglTexCoord3fv               = NULL;
	qglTexCoord3i                = NULL;
	qglTexCoord3iv               = NULL;
	qglTexCoord3s                = NULL;
	qglTexCoord3sv               = NULL;
	qglTexCoord4d                = NULL;
	qglTexCoord4dv               = NULL;
	qglTexCoord4f                = NULL;
	qglTexCoord4fv               = NULL;
	qglTexCoord4i                = NULL;
	qglTexCoord4iv               = NULL;
	qglTexCoord4s                = NULL;
	qglTexCoord4sv               = NULL;
	qglTexCoordPointer           = NULL;
	qglTexEnvf                   = NULL;
	qglTexEnvfv                  = NULL;
	qglTexEnvi                   = NULL;
	qglTexEnviv                  = NULL;
	qglTexGend                   = NULL;
	qglTexGendv                  = NULL;
	qglTexGenf                   = NULL;
	qglTexGenfv                  = NULL;
	qglTexGeni                   = NULL;
	qglTexGeniv                  = NULL;
	qglTexImage1D                = NULL;
	qglTexImage2D                = NULL;
	qglTexParameterf             = NULL;
	qglTexParameterfv            = NULL;
	qglTexParameteri             = NULL;
	qglTexParameteriv            = NULL;
	qglTexSubImage1D             = NULL;
	qglTexSubImage2D             = NULL;
	qglTranslated                = NULL;
	qglTranslatef                = NULL;
	qglVertex2d                  = NULL;
	qglVertex2dv                 = NULL;
	qglVertex2f                  = NULL;
	qglVertex2fv                 = NULL;
	qglVertex2i                  = NULL;
	qglVertex2iv                 = NULL;
	qglVertex2s                  = NULL;
	qglVertex2sv                 = NULL;
	qglVertex3d                  = NULL;
	qglVertex3dv                 = NULL;
	qglVertex3f                  = NULL;
	qglVertex3fv                 = NULL;
	qglVertex3i                  = NULL;
	qglVertex3iv                 = NULL;
	qglVertex3s                  = NULL;
	qglVertex3sv                 = NULL;
	qglVertex4d                  = NULL;
	qglVertex4dv                 = NULL;
	qglVertex4f                  = NULL;
	qglVertex4fv                 = NULL;
	qglVertex4i                  = NULL;
	qglVertex4iv                 = NULL;
	qglVertex4s                  = NULL;
	qglVertex4sv                 = NULL;
	qglVertexPointer             = NULL;
	qglViewport                  = NULL;
}